### ISSUE TITLE
Latest tag points to 7.4.28

### ISSUE THREAD

**Issue by bobvandevijver** [renovatebot/docker-php#60]
Not sure if this is the right place, but the latest tag currently points to 7.4.28, while I would expect that to be 8.1.4 (and I have no clue on how to update it).

```
bobv@gitlab-runner:~$ sudo docker run --rm -it docker.io/renovate/php:latest php -v
Unable to find image 'renovate/php:latest' locally
latest: Pulling from renovate/php
4d32b49e2995: Already exists
a373e0446ac8: Already exists
41eb12f87f0e: Already exists
f17f6d8756d7: Already exists
321ae97d74e5: Already exists
61ee350fd91b: Pull complete
Digest: sha256:7537600a509b82c82be249596f16de13f53eb97f96217e57d0a425bba3979f84
Status: Downloaded newer image for renovate/php:latest
PHP 7.4.28 (cli) (built: Feb 18 2022 01:25:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies
```

**Comment by viceice** [comment]
we're currently try to retain best compatibility with older composer and user requirements.

so if we move to V8, it potentially break a lot users.

how do you use this image? it's only supported usage is by renovate docker sidecars.

**Comment by bobvandevijver** [comment]
I am using it with sidecars :) 

I only stumbled upon it as it was pulled for a composer file that did not have a php constraint defined, making it fallback to `latest` which has not been an issue for me until now. Somehow this is not (yet?) triggered in other projects with the same composer file for the code style tooling (this is the composer definition: https://github.com/Drenso/symfony-oidc/blob/bfec103d6fdf57ceee5527febc63281e5ac81471/cs_tools/composer.json). I have now added the PHP version to the file so it should be solved anyways, but it did make me wonder why 7.4 was considered to be `latest` as I got the following on a PHP 8+ project:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/console v6.0.5 requires php >=8.0.2 -> your php version (7.4.28) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v3.8.0 requires symfony/console ^5.4 || ^6.0 -> satisfiable by symfony/console[v6.0.5].
    - friendsofphp/php-cs-fixer is locked to version v3.8.0 and an update of this package was not requested.
```

The reason sounds valid, so I'm fine with keeping it as it is and closing this issue. :+1:

I do want to mention that a lot of projects have already moved on to PHP 8, requiring at least PHP 8 with their latest release (Symfony 6 being one of them) or at least support it. Looking at the [Packagist stats](https://packagist.org/php-statistics), PHP 7.4 and PHP 8+ both have around 40% of the installs, so it might be nice to already to the step to make PHP 8 the `latest` here.

**Comment by rarkins** [comment]
Is there a way for us to detect when a project is PHP 8? Eg lock file difference

**Comment by bobvandevijver** [comment]
Projects usually define a php constraint in their composer configuration file, as I now also explicitly did for the configuration I mentioned before: https://github.com/Drenso/symfony-oidc/blob/68cb73d74d615bb4584830dfd6818e859603c31e/cs_tools/composer.json.

The lock file also contains all php requirements (if set) for the dependencies, as example: https://github.com/Drenso/symfony-oidc/blob/68cb73d74d615bb4584830dfd6818e859603c31e/cs_tools/composer.lock#L852.
