### ISSUE TITLE
add composer user installer

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-php#7]
https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

ref: https://github.com/renovatebot/renovate/issues/2355

Idea:
* add `~/bin` to path
* download composer-setup to `~/bin/composer-setup` (make executable)
* renovate runs `composer-setup --install-dir=$HOME/bin --filename=composer [--version=1.10.0]` as preCommands

@rarkins should we add a wrapper script for `composer-setup`, so renovate only has to run `install-composer 1.10.0` ?

**Comment by rarkins** [comment]
Good idea.
